services:
  backend:
    build:
      context: ./backend
    image: arthurhenriquedev/3tec-talkie-backend:latest
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
    image: arthurhenriquedev/3tec-talkie-frontend:latest
    ports:
      - '3000:3000'
    depends_on:
      - backend
