services:
  backend:
    build:
      context: ./backend
    ports:
      - '4000:3000'  # O backend será acessível apenas localmente
    environment:
      NODE_ENV: production  # Configure outras variáveis de ambiente, se necessário
      DB_TYPE: mysql
      DB_HOST: mysql  # Nome do serviço do MySQL
      DB_PORT: 3307
      DB_USERNAME: seu_usuario
      DB_PASSWORD: sua_senha
      DB_DATABASE: channels_db
    depends_on:
      - mysql  # Adicionando dependência do MySQL

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'  # O frontend será acessível externamente
    depends_on:
      - backend

  mysql:
      image: mysql/mysql-server:8.0  # Use uma imagem compatível com ARM
      environment:
        MYSQL_ROOT_PASSWORD: sua_senha  # Senha do root (opcional)
        MYSQL_DATABASE: channels_db  # Cria automaticamente o banco de dados
        MYSQL_USER: seu_usuario  # Usuário que você especificou
        MYSQL_PASSWORD: sua_senha  # Senha do usuário
      ports:
        - '3307:3306'  # Porta do MySQL